### ISSUE TITLE
The termux version has not fixed the victim's public ip problem

### ISSUE THREAD

**Issue by Micrafast** [An0nUD4Y/SocialFish#42] opened 2018-06-08 14:28 UTC
I found that the problem of the termux version of the victim's public IP has not been solved yet. I tried it once, but I found that I had to make many modifications on PHP. However, my PHP is not good. If you have time, you can solve it. Thank you.

**Comment by usama7628674** [comment] 2018-06-08 15:06
@Micrafast Last time I tried termux version it was complete mess I'll look into it soon.

**Comment by usama7628674** [comment] 2018-06-09 04:38
@Micrafast @alexmozzhakov @An0nUD4Y socialfish updated and fixed to work in termux.Closing now

**Comment by An0nUD4Y** [comment] 2018-06-09 07:39
@usama7628674  it seems that there is still some issues present in SocialFishTermux version,  Please make sure you have tested it,  Because its not working for me....

**Comment by An0nUD4Y** [comment] 2018-06-09 07:46
SF-An0nUD4Y > 1
touch: Server/www/usernames.txt: No such file or directory
sh: ./Server/ngrok: not found

 [*] Ngrok URL:
[*] Hi Hacker Everything has been completed.............. Start HAcking

   _.-=-._     .-,
 .'       "-.,' /
(  AnonUD4Y_  ~.<
 `=.____.="  `._\

 [*] NOW YOU WILL GET YOUR VICTIM'S LIVE INFORMATION .
 [*] GET VICTIM'S IP ADDRESS, ISP, GEOLOCATION, CITY, COUNTRY, AND MANY MORE STUFF.
 [*] Waiting for credentials & victim's info...

Traceback (most recent call last):
  File "./SocialFishTermux.py", line 272, in <module>
    waitCreds()
  File "./SocialFishTermux.py", line 135, in waitCreds
    with open('Server/www/usernames.txt') as creds:
IOError: [Errno 2] No such file or directory: 'Server/www/usernames.txt'
PHP 7.2.6 Development Server started at Sat Jun  9 13:01:27 2018
Listening on http://127.0.0.1:1111
Document root is /data/data/com.termux/files/home/SocialFish/Server/www
Press Ctrl-C to quit.``

**Comment by An0nUD4Y** [comment] 2018-06-09 07:48
@usama7628674  Please check it out ....

**Comment by An0nUD4Y** [comment] 2018-06-09 08:03
@usama7628674  I found the problem,  

The problem is with Usernames.txt in Server/www 
But when i manually created a file named usernames.txt .... It starts working for me... So please resolve it ...


Thank You !

**Comment by usama7628674** [comment] 2018-06-09 09:30
@An0nUD4Y Fixed please retest

**Closed** 2018-06-09 13:41 UTC
